version: '3.7'

# networks:
#   kong-net:
#     external: false

services:
  kong:
    build: .
      # network: host
    environment: 
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl 
    ports: 
      - '8000:8000'
      - '8443:8443'
      - '127.0.0.1:8001:8001'
      - '127.0.0.1:8444:8444'
    # networks:
    #   - kong-net